/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAepPsRouteImport } from './routes/_layout/aep-ps'
import { Route as LayoutCadastrosRouteImport } from './routes/_layout/cadastros'
import { Route as LayoutImportacaoRouteImport } from './routes/_layout/importacao'
import { Route as LayoutMatrizRouteImport } from './routes/_layout/matriz'
import { Route as LayoutPlanoDeAcaoRouteImport } from './routes/_layout/plano-de-acao'
import { Route as LayoutRelatoriosRouteImport } from './routes/_layout/relatorios'
import { Route as LayoutResultadosRouteImport } from './routes/_layout/resultados'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAepPsRoute = LayoutAepPsRouteImport.update({ id: '/aep-ps', path: '/aep-ps', getParentRoute: () => LayoutRoute } as any)
const LayoutCadastrosRoute = LayoutCadastrosRouteImport.update({ id: '/cadastros', path: '/cadastros', getParentRoute: () => LayoutRoute } as any)
const LayoutImportacaoRoute = LayoutImportacaoRouteImport.update({ id: '/importacao', path: '/importacao', getParentRoute: () => LayoutRoute } as any)
const LayoutMatrizRoute = LayoutMatrizRouteImport.update({ id: '/matriz', path: '/matriz', getParentRoute: () => LayoutRoute } as any)
const LayoutPlanoDeAcaoRoute = LayoutPlanoDeAcaoRouteImport.update({ id: '/plano-de-acao', path: '/plano-de-acao', getParentRoute: () => LayoutRoute } as any)
const LayoutRelatoriosRoute = LayoutRelatoriosRouteImport.update({ id: '/relatorios', path: '/relatorios', getParentRoute: () => LayoutRoute } as any)
const LayoutResultadosRoute = LayoutResultadosRouteImport.update({ id: '/resultados', path: '/resultados', getParentRoute: () => LayoutRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/aep-ps': typeof LayoutAepPsRoute
  '/cadastros': typeof LayoutCadastrosRoute
  '/importacao': typeof LayoutImportacaoRoute
  '/matriz': typeof LayoutMatrizRoute
  '/plano-de-acao': typeof LayoutPlanoDeAcaoRoute
  '/relatorios': typeof LayoutRelatoriosRoute
  '/resultados': typeof LayoutResultadosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/aep-ps': typeof LayoutAepPsRoute
  '/cadastros': typeof LayoutCadastrosRoute
  '/importacao': typeof LayoutImportacaoRoute
  '/matriz': typeof LayoutMatrizRoute
  '/plano-de-acao': typeof LayoutPlanoDeAcaoRoute
  '/relatorios': typeof LayoutRelatoriosRoute
  '/resultados': typeof LayoutResultadosRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/aep-ps': typeof LayoutAepPsRoute
  '/_layout/cadastros': typeof LayoutCadastrosRoute
  '/_layout/importacao': typeof LayoutImportacaoRoute
  '/_layout/matriz': typeof LayoutMatrizRoute
  '/_layout/plano-de-acao': typeof LayoutPlanoDeAcaoRoute
  '/_layout/relatorios': typeof LayoutRelatoriosRoute
  '/_layout/resultados': typeof LayoutResultadosRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/aep-ps'
    | '/cadastros'
    | '/importacao'
    | '/matriz'
    | '/plano-de-acao'
    | '/relatorios'
    | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/aep-ps'
    | '/cadastros'
    | '/importacao'
    | '/matriz'
    | '/plano-de-acao'
    | '/relatorios'
    | '/resultados'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/aep-ps'
    | '/_layout/cadastros'
    | '/_layout/importacao'
    | '/_layout/matriz'
    | '/_layout/plano-de-acao'
    | '/_layout/relatorios'
    | '/_layout/resultados'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/aep-ps': { id: '/_layout/aep-ps'; path: '/aep-ps'; fullPath: '/aep-ps'; preLoaderRoute: typeof LayoutAepPsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/cadastros': { id: '/_layout/cadastros'; path: '/cadastros'; fullPath: '/cadastros'; preLoaderRoute: typeof LayoutCadastrosRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/importacao': { id: '/_layout/importacao'; path: '/importacao'; fullPath: '/importacao'; preLoaderRoute: typeof LayoutImportacaoRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/matriz': { id: '/_layout/matriz'; path: '/matriz'; fullPath: '/matriz'; preLoaderRoute: typeof LayoutMatrizRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/plano-de-acao': { id: '/_layout/plano-de-acao'; path: '/plano-de-acao'; fullPath: '/plano-de-acao'; preLoaderRoute: typeof LayoutPlanoDeAcaoRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/relatorios': { id: '/_layout/relatorios'; path: '/relatorios'; fullPath: '/relatorios'; preLoaderRoute: typeof LayoutRelatoriosRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/resultados': { id: '/_layout/resultados'; path: '/resultados'; fullPath: '/resultados'; preLoaderRoute: typeof LayoutResultadosRouteImport; parentRoute: typeof LayoutRoute }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAepPsRoute: typeof LayoutAepPsRoute
  LayoutCadastrosRoute: typeof LayoutCadastrosRoute
  LayoutImportacaoRoute: typeof LayoutImportacaoRoute
  LayoutMatrizRoute: typeof LayoutMatrizRoute
  LayoutPlanoDeAcaoRoute: typeof LayoutPlanoDeAcaoRoute
  LayoutRelatoriosRoute: typeof LayoutRelatoriosRoute
  LayoutResultadosRoute: typeof LayoutResultadosRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAepPsRoute: LayoutAepPsRoute,
  LayoutCadastrosRoute: LayoutCadastrosRoute,
  LayoutImportacaoRoute: LayoutImportacaoRoute,
  LayoutMatrizRoute: LayoutMatrizRoute,
  LayoutPlanoDeAcaoRoute: LayoutPlanoDeAcaoRoute,
  LayoutRelatoriosRoute: LayoutRelatoriosRoute,
  LayoutResultadosRoute: LayoutResultadosRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
