import { AlignmentType, BorderStyle, Document, Footer, Header, HeadingLevel, HeightRule, ImageRun, PageBreak, PageNumber, Packer, Paragraph, ShadingType, Table, TableCell, TableOfContents, TableRow, TextRun, VerticalAlign, WidthType } from "docx"
import type { AepAssessment, AepEvidence, AssessmentCycle, Company, CompanyStructure, DrpsResult, Ghe } from "@/lib/psychosocialApi"

const BLUE = "337DB7", LIGHT = "D9E8F5", PALE = "EEF5FB", WHITE = "FFFFFF", INK = "17212B", MUTED = "52606D", WIDTH = 10766
const borders = { top: { style: BorderStyle.SINGLE, size: 4, color: BLUE }, bottom: { style: BorderStyle.SINGLE, size: 4, color: BLUE }, left: { style: BorderStyle.SINGLE, size: 4, color: BLUE }, right: { style: BorderStyle.SINGLE, size: 4, color: BLUE } }
const riskLabel = { irrelevante: "Irrelevante", baixo: "Baixo", médio: "Médio", alto: "Alto", crítico: "Crítico" }
const actions: Record<string, string> = {
  DEM: "Revisar volume, ritmo, prioridades, prazos e distribuição das atividades.", CON: "Ampliar participação e autonomia compatíveis com as responsabilidades.", APL: "Fortalecer orientação, apoio e feedback das lideranças.", APE: "Aprimorar cooperação, comunicação e suporte entre trabalhadores.", REL: "Prevenir conflitos e fortalecer relações respeitosas entre equipes.", CLA: "Formalizar atribuições, prioridades e expectativas de desempenho.", MUD: "Planejar, comunicar e acompanhar mudanças organizacionais.", REC: "Estruturar práticas transparentes de feedback e reconhecimento.", EQU: "Revisar jornada, pausas, previsibilidade e demandas fora do horário.", ASS: "Fortalecer segurança psicológica, canais e procedimentos de apuração.",
}
const factorDescriptions: Record<string, string> = {
  DEM: "volume de trabalho, ritmo, pressão por resultados, prazos, pausas e compatibilidade entre exigências e recursos disponíveis",
  CON: "possibilidade de participação, influência sobre o modo de execução, uso de competências e autonomia compatível com as responsabilidades",
  APL: "disponibilidade da liderança, orientação, escuta, feedback, apoio diante de dificuldades e tratamento coerente das demandas",
  APE: "cooperação, comunicação, confiança, compartilhamento de informações e suporte entre colegas e equipes",
  REL: "qualidade das relações socioprofissionais, respeito, tratamento de conflitos, comunicação e prevenção de comportamentos hostis",
  CLA: "compreensão das atribuições, responsabilidades, prioridades, interfaces, limites de atuação e resultados esperados",
  MUD: "planejamento, comunicação, participação e suporte oferecidos durante alterações de processos, estrutura, tecnologia ou gestão",
  REC: "percepção de valorização, retorno sobre o desempenho, justiça, oportunidades e reconhecimento das contribuições profissionais",
  EQU: "compatibilidade entre jornada, recuperação, demandas fora do horário e conciliação entre trabalho e vida pessoal",
  ASS: "respeito, dignidade, liberdade para manifestação, canais seguros e prevenção de assédio, violência, discriminação ou retaliação",
}
const riskMeaning: Record<string, string> = {
  irrelevante: "condição aceitável no recorte avaliado, sem indicação de medida adicional além da manutenção dos controles",
  baixo: "condição globalmente favorável, que requer preservação dos controles e monitoramento preventivo",
  médio: "condição que demanda plano de ação estruturado, análise das causas organizacionais e acompanhamento da eficácia",
  alto: "condição prioritária, com necessidade de medidas preventivas em prazo reduzido e validação pela gestão",
  crítico: "condição que requer avaliação e intervenção imediata, com definição formal de responsáveis e controles",
}
export type AepReportBundle = { ghe: Ghe; sectorName: string; assessment: AepAssessment | null; evidences: AepEvidence[] }
type Input = { company: Company; cycle: AssessmentCycle; structure: CompanyStructure; drps: DrpsResult; aep: AepReportBundle[]; mode: "rtirp" | "integration"; logoData?: ArrayBuffer; flowData?: ArrayBuffer }

function run(value: string, bold = false, color = INK, size = 19) { return new TextRun({ text: value, bold, color, size, font: "Arial" }) }
function para(value: string, options: { bold?: boolean; color?: string; size?: number; align?: (typeof AlignmentType)[keyof typeof AlignmentType]; before?: number; after?: number } = {}) { return new Paragraph({ alignment: options.align ?? AlignmentType.JUSTIFIED, spacing: { before: options.before ?? 0, after: options.after ?? 110, line: 276 }, children: [run(value, options.bold, options.color, options.size)] }) }
function cell(value: string, width: number, options: { bold?: boolean; fill?: string; color?: string; align?: (typeof AlignmentType)[keyof typeof AlignmentType]; size?: number } = {}) { return new TableCell({ width: { size: width, type: WidthType.DXA }, borders, shading: options.fill ? { type: ShadingType.CLEAR, fill: options.fill } : undefined, verticalAlign: VerticalAlign.CENTER, margins: { top: 110, bottom: 110, left: 130, right: 130 }, children: [para(value || "—", { bold: options.bold, color: options.color, size: options.size ?? 17, align: options.align, after: 0 })] }) }
function table(rows: TableRow[], widths: number[]) { return new Table({ rows, width: { size: WIDTH, type: WidthType.DXA }, columnWidths: widths, layout: "fixed" }) }
function section(number: string, title: string) { return new Paragraph({ heading: HeadingLevel.HEADING_1, shading: { type: ShadingType.CLEAR, fill: BLUE }, spacing: { before: 180, after: 130 }, indent: { left: 120, right: 120 }, children: [run(`${number} - ${title}`, true, WHITE, 22)] }) }
function subsection(title: string) { return new Paragraph({ heading: HeadingLevel.HEADING_2, alignment: AlignmentType.LEFT, spacing: { before: 180, after: 90 }, children: [run(title, true, BLUE, 21)] }) }
function breakPage() { return new Paragraph({ children: [new PageBreak()] }) }
function headerRow(labels: string[], widths: number[]) { return new TableRow({ tableHeader: true, children: labels.map((label, index) => cell(label, widths[index], { bold: true, fill: LIGHT, align: AlignmentType.CENTER, size: 15 })) }) }
function safe(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") }

async function build(input: Input) {
  const { company, cycle, structure, drps, aep, mode, logoData, flowData } = input
  const completed = aep.filter((item) => item.assessment?.completed_at)
  const pending = aep.filter((item) => !item.assessment?.completed_at)
  const allEvidence = aep.reduce((sum, item) => sum + item.evidences.length, 0)
  const totalWorkers = structure.ghes.reduce((sum, ghe) => sum + ghe.worker_count, 0)
  const participationRate = totalWorkers > 0 ? Math.min(100, (drps.respondent_count / totalWorkers) * 100) : undefined
  const integration = drps.dimensions.map((dimension) => {
    const scores = completed.flatMap((bundle) => bundle.assessment?.answers.filter((answer) => answer.item_code.startsWith(`${dimension.code}.`)).map((answer) => answer.score) ?? [])
    const aepMax = scores.length ? Math.max(...scores) : undefined
    const drpsUnfavorable = ["médio", "alto", "crítico"].includes(dimension.risk)
    const aepUnfavorable = aepMax === undefined ? undefined : aepMax >= 2
    const status = aepUnfavorable === undefined ? "Pendente" : drpsUnfavorable === aepUnfavorable ? (drpsUnfavorable ? "Convergência de risco" : "Convergência favorável") : "Divergência"
    const referral = status === "Convergência de risco" ? "Priorizar no PGR" : status === "Convergência favorável" ? "Manter controles" : status === "Divergência" ? "Aprofundar evidências" : "Concluir AEP-PS"
    return { ...dimension, aepMax, status, referral }
  })
  const flagged = integration.filter((item) => item.status === "Convergência de risco" || item.status === "Divergência")
  const priority = flagged.length ? flagged : [...integration].sort((a, b) => b.mean - a.mean).slice(0, 2)
  const rankedDimensions = [...integration].sort((a, b) => b.mean - a.mean)
  const principal = rankedDimensions[0]
  const secondary = rankedDimensions[1]
  const elevatedCount = integration.filter((item) => ["médio", "alto", "crítico"].includes(item.risk)).length
  const metaW = [1900, 3483, 1900, 3483]
  const meta = table([
    new TableRow({ children: [cell("EMPRESA", metaW[0], { bold: true, fill: LIGHT }), cell(company.trade_name || company.legal_name, metaW[1]), cell("CNPJ", metaW[2], { bold: true, fill: LIGHT }), cell(company.cnpj, metaW[3])] }),
    new TableRow({ children: [cell("CICLO", metaW[0], { bold: true, fill: LIGHT }), cell(cycle.name, metaW[1]), cell("DATA", metaW[2], { bold: true, fill: LIGHT }), cell(new Date(`${cycle.assessment_date}T12:00:00`).toLocaleDateString("pt-BR"), metaW[3])] }),
    new TableRow({ children: [cell("ABRANGÊNCIA", metaW[0], { bold: true, fill: LIGHT }), cell(`${structure.sectors.length} setor(es) · ${structure.ghes.length} GHE(s)`, metaW[1]), cell("SITUAÇÃO", metaW[2], { bold: true, fill: LIGHT }), cell(pending.length ? "Relatório parcial" : "Ciclo integrado", metaW[3], { bold: true, fill: pending.length ? "FFF2CC" : "DCEBD2" })] }),
  ], metaW)
  const intW = [2700, 1450, 1450, 2866, 2300]
  const intRows = [headerRow(["Dimensão", "DRPS", "AEP-PS", "Integração", "Encaminhamento"], intW), ...integration.map((item) => new TableRow({ cantSplit: true, children: [cell(item.name, intW[0]), cell(`${item.mean.toFixed(2).replace(".", ",")} · ${riskLabel[item.risk]}`, intW[1], { align: AlignmentType.CENTER, size: 15 }), cell(item.aepMax === undefined ? "Pendente" : String(item.aepMax), intW[2], { align: AlignmentType.CENTER }), cell(item.status, intW[3], { bold: true, fill: item.status === "Convergência de risco" ? "F8D7DA" : item.status === "Divergência" ? "FFF2CC" : PALE, align: AlignmentType.CENTER, size: 15 }), cell(item.referral, intW[4], { size: 15 })] }))]
  const aepW = [2900, 2500, 1700, 1666, 2000]
  const aepRows = [headerRow(["Setor", "GHE", "Situação", "Evidências", "Maior nota AEP"], aepW), ...aep.map((bundle) => { const scores = bundle.assessment?.answers.map((answer) => answer.score) ?? []; return new TableRow({ cantSplit: true, children: [cell(bundle.sectorName, aepW[0]), cell(bundle.ghe.name, aepW[1]), cell(bundle.assessment?.completed_at ? "Concluída" : bundle.assessment ? "Rascunho" : "Não iniciada", aepW[2], { align: AlignmentType.CENTER }), cell(String(bundle.evidences.length), aepW[3], { align: AlignmentType.CENTER }), cell(scores.length ? String(Math.max(...scores)) : "—", aepW[4], { align: AlignmentType.CENTER })] }) })]
  const recW = [2400, 4566, 1700, 2100]
  const recRows = [headerRow(["Fator", "Recomendação técnica", "Prazo orientativo", "Indicador sugerido"], recW), ...(priority.length ? priority.map((item) => new TableRow({ cantSplit: true, children: [cell(item.name, recW[0], { bold: true }), cell(actions[item.code] ?? "Avaliar medida preventiva compatível com os achados.", recW[1]), cell(item.status === "Convergência de risco" ? "Até 90 dias" : "Até 180 dias", recW[2], { align: AlignmentType.CENTER }), cell("Registro da medida e verificação da condição", recW[3])] })) : [new TableRow({ children: [cell("Manter os controles existentes e realizar verificação periódica.", WIDTH)] })])]
  const header = new Header({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: logoData ? [new ImageRun({ data: logoData, type: "png", transformation: { width: 168, height: 55 } })] : [run("SEALAB MEDICINA OCUPACIONAL", true, BLUE, 22)] })] })
  const footer = new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [run("Metodologia Sealab  |  ", false, MUTED, 16), new TextRun({ children: ["Página ", PageNumber.CURRENT, " de ", PageNumber.TOTAL_PAGES], font: "Arial", size: 16, color: MUTED })] })] })
  const blankHeader = new Header({ children: [new Paragraph({})] })
  const blankFooter = new Footer({ children: [new Paragraph({})] })
  const title = mode === "rtirp" ? "RELATÓRIO TÉCNICO INTEGRADO DE RISCOS PSICOSSOCIAIS" : "ORIENTAÇÕES PARA INTEGRAÇÃO AO GRO/PGR"
  const reportDate = new Date(`${cycle.assessment_date}T12:00:00`).toLocaleDateString("pt-BR")
  const cover = mode === "rtirp" ? [
    para("", { after: 220 }),
    new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 700 }, children: logoData ? [new ImageRun({ data: logoData, type: "png", transformation: { width: 260, height: 85 } })] : [run("SEALAB MEDICINA OCUPACIONAL", true, BLUE, 28)] }),
    para("RELATÓRIO TÉCNICO INTEGRADO", { bold: true, color: BLUE, size: 42, align: AlignmentType.CENTER, after: 70 }),
    para("DE RISCOS PSICOSSOCIAIS", { bold: true, color: INK, size: 34, align: AlignmentType.CENTER, after: 90 }),
    para("Diagnóstico organizacional, integração DRPS × AEP-PS, plano de ação e programa de monitoramento", { color: MUTED, size: 21, align: AlignmentType.CENTER, after: 650 }),
    table([
      new TableRow({ children: [cell("EMPRESA", 2500, { bold: true, fill: LIGHT }), cell(company.legal_name, 8266, { bold: true, size: 20 })] }),
      new TableRow({ children: [cell("CNPJ", 2500, { bold: true, fill: LIGHT }), cell(company.cnpj, 8266)] }),
      new TableRow({ children: [cell("CICLO AVALIATIVO", 2500, { bold: true, fill: LIGHT }), cell(cycle.name, 8266)] }),
      new TableRow({ children: [cell("DATA DA AVALIAÇÃO", 2500, { bold: true, fill: LIGHT }), cell(reportDate, 8266)] }),
      new TableRow({ children: [cell("RESPONSÁVEIS TÉCNICOS", 2500, { bold: true, fill: LIGHT }), cell("Identificação e assinaturas digitais constantes no item 15.2", 8266)] }),
    ], [2500, 8266]),
    para("RTIRP · Metodologia Integrada Sealab · Revisão 00", { bold: true, color: BLUE, size: 17, align: AlignmentType.CENTER, before: 650, after: 0 }),
    breakPage(),
    para("SUMÁRIO", { bold: true, color: BLUE, size: 30, align: AlignmentType.CENTER, after: 260 }),
    new TableOfContents("Sumário", { hyperlink: true, headingStyleRange: "1-1" }),
    para("Nota: o sumário e a numeração das páginas são atualizados automaticamente ao abrir o arquivo no Microsoft Word.", { color: MUTED, size: 16, before: 260, after: 0 }),
    breakPage(),
  ] : []
  const opening = [...cover, para(title, { bold: true, color: BLUE, size: 27, align: AlignmentType.CENTER, after: 60 }), para(mode === "rtirp" ? "Diagnóstico organizacional, integração AEP-PS e recomendações técnicas" : "Resumo técnico DRPS × AEP-PS", { color: MUTED, size: 18, align: AlignmentType.CENTER, after: 220 })]
  const statusParagraph = pending.length
    ? para(`DOCUMENTO PARCIAL: permanecem pendentes as AEP-PS de ${pending.map((item) => `${item.sectorName} / ${item.ghe.name}`).join("; ")}. O parecer deverá ser atualizado após a conclusão dessas avaliações.`, { color: "8A5A00", bold: true, after: 150 })
    : para("Todas as AEP-PS dos GHEs cadastrados foram concluídas, permitindo a consolidação integrada do ciclo.", { after: 150 })
  const controlW = [3300, 7466]
  const controlTable = table([
    headerRow(["Item", "Informação"], controlW),
    new TableRow({ children: [cell("Documento", controlW[0]), cell("Relatório Técnico Integrado de Riscos Psicossociais", controlW[1])] }),
    new TableRow({ children: [cell("Empresa", controlW[0]), cell(company.legal_name, controlW[1])] }),
    new TableRow({ children: [cell("Metodologia", controlW[0]), cell("DRPS Sealab + AEP-PS por GHE", controlW[1])] }),
    new TableRow({ children: [cell("Base técnica", controlW[0]), cell("HSE-IT adaptado, NR-01, NR-17 e ISO 45003", controlW[1])] }),
    new TableRow({ children: [cell("Emissão", controlW[0]), cell(new Date().toLocaleDateString("pt-BR"), controlW[1])] }),
    new TableRow({ children: [cell("Revisão", controlW[0]), cell("00", controlW[1])] }),
    new TableRow({ children: [cell("Validade orientativa", controlW[0]), cell("12 meses ou até mudança relevante nas condições avaliadas", controlW[1])] }),
  ], controlW)
  const summaryW = [5383, 5383]
  const summaryTable = table([
    headerRow(["Indicador", "Resultado"], summaryW),
    new TableRow({ children: [cell("Respondentes válidos no DRPS", summaryW[0]), cell(String(drps.respondent_count), summaryW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Índice geral psicossocial", summaryW[0]), cell(drps.general_mean.toFixed(2).replace(".", ","), summaryW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Classificação geral", summaryW[0]), cell(riskLabel[drps.overall_risk], summaryW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Principal fator DRPS", summaryW[0]), cell(drps.dimensions.find((item) => item.code === drps.priority_dimension)?.name ?? drps.priority_dimension, summaryW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("AEP-PS concluídas", summaryW[0]), cell(`${completed.length} de ${aep.length} GHEs`, summaryW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Evidências anexadas", summaryW[0]), cell(String(allEvidence), summaryW[1], { align: AlignmentType.CENTER })] }),
  ], summaryW)
  const riskW = [2800, 4166, 1800, 2000]
  const riskRows = [headerRow(["Fator prioritário", "Recomendação técnica", "Prazo", "Indicador"], riskW), ...(priority.length ? priority.map((item) => new TableRow({ cantSplit: true, children: [cell(item.name, riskW[0], { bold: true }), cell(actions[item.code] ?? "Avaliar medida preventiva compatível com os achados.", riskW[1]), cell(item.status === "Convergência de risco" ? "Até 90 dias" : "Até 180 dias", riskW[2], { align: AlignmentType.CENTER }), cell("Registro e verificação da condição", riskW[3])] })) : [new TableRow({ children: [cell("Manter controles e realizar verificação periódica.", WIDTH)] })])]
  const participationW = [5383, 5383]
  const participationTable = table([
    headerRow(["Indicador", "Resultado"], participationW),
    new TableRow({ children: [cell("Trabalhadores cadastrados nos GHEs", participationW[0]), cell(totalWorkers ? String(totalWorkers) : "Não informado", participationW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Respondentes válidos", participationW[0]), cell(String(drps.respondent_count), participationW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("Taxa de participação estimada", participationW[0]), cell(participationRate === undefined ? "Não calculável" : `${participationRate.toFixed(1).replace(".", ",")}%`, participationW[1], { align: AlignmentType.CENTER })] }),
    new TableRow({ children: [cell("GHEs abrangidos na estrutura", participationW[0]), cell(String(structure.ghes.length), participationW[1], { align: AlignmentType.CENTER })] }),
  ], participationW)
  const levelW = [2400, 4566, 3800]
  const levelTable = table([
    headerRow(["Classificação", "Interpretação", "Encaminhamento orientativo"], levelW),
    new TableRow({ children: [cell("Crítico", levelW[0], { bold: true, fill: "F4CCCC" }), cell(riskMeaning.crítico, levelW[1]), cell("Intervenção imediata", levelW[2])] }),
    new TableRow({ children: [cell("Alto", levelW[0], { bold: true, fill: "FCE5CD" }), cell(riskMeaning.alto, levelW[1]), cell("Ação prioritária, preferencialmente até 90 dias", levelW[2])] }),
    new TableRow({ children: [cell("Médio", levelW[0], { bold: true, fill: "FFF2CC" }), cell(riskMeaning.médio, levelW[1]), cell("Plano de ação, preferencialmente até 180 dias", levelW[2])] }),
    new TableRow({ children: [cell("Baixo", levelW[0], { bold: true, fill: "D9EAD3" }), cell(riskMeaning.baixo, levelW[1]), cell("Monitoramento e revisão periódica", levelW[2])] }),
    new TableRow({ children: [cell("Irrelevante", levelW[0], { bold: true, fill: "EAF4E4" }), cell(riskMeaning.irrelevante, levelW[1]), cell("Manutenção das condições", levelW[2])] }),
  ], levelW)
  const descW = [2900, 7866]
  const descriptionTable = table([headerRow(["Fator", "O que é avaliado"], descW), ...integration.map((item) => new TableRow({ cantSplit: true, children: [cell(item.name, descW[0], { bold: true }), cell(factorDescriptions[item.code] ?? "aspectos da organização e das relações de trabalho", descW[1])] }))], descW)
  const evidenceW = [2500, 2300, 1700, 4266]
  const evidenceRows = [headerRow(["Setor / GHE", "Fonte", "Vínculo", "Descrição / arquivo"], evidenceW), ...aep.flatMap((bundle) => bundle.evidences.map((evidence) => new TableRow({ cantSplit: true, children: [cell(`${bundle.sectorName} / ${bundle.ghe.name}`, evidenceW[0]), cell(evidence.category, evidenceW[1]), cell(evidence.item_code ?? "Geral", evidenceW[2]), cell(evidence.description || evidence.filename, evidenceW[3])] })))]
  let children: Array<Paragraph | Table> = [...opening]
  if (mode === "rtirp") {
    children = [...children,
      section("1", "CONTROLE DO DOCUMENTO"), controlTable, para("", { after: 100 }),
      section("2", "FLUXO METODOLÓGICO DA AVALIAÇÃO"), para("A metodologia integrada Sealab é executada em etapas complementares: planejamento e definição do escopo; cadastro da estrutura organizacional e dos GHEs; aplicação do DRPS; validação e análise da percepção coletiva; realização da AEP-PS em campo; coleta e análise das evidências; integração dos achados; definição das prioridades e recomendações; e emissão deste RTIRP.", { before: 130 }), ...(flowData ? [new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 120, after: 80 }, children: [new ImageRun({ data: flowData, type: "png", transformation: { width: 690, height: 327 } })] }), para("Figura 1 – Fluxo metodológico utilizado para elaboração do Diagnóstico e do Relatório Técnico Integrado de Riscos Psicossociais.", { color: MUTED, size: 16, align: AlignmentType.CENTER, after: 180 })] : [para("DRPS (percepção coletiva) → AEP-PS por GHE (avaliação técnica da atividade real) → análise das evidências → matriz de convergência e divergência → recomendações ao GRO/PGR → emissão do RTIRP.", { bold: true, color: BLUE, align: AlignmentType.CENTER, after: 180 })]),
      section("3", "DADOS DA EMPRESA"), meta, para("", { after: 100 }),
      section("4", "RESUMO"), summaryTable,
      subsection("Principais achados"), para(`A organização apresentou índice geral psicossocial de ${drps.general_mean.toFixed(2).replace(".", ",")} e classificação geral de risco ${riskLabel[drps.overall_risk]}. Esse resultado representa o cenário médio das dez dimensões avaliadas, interpretado conforme os critérios de probabilidade, severidade e prioridade de ação da metodologia Sealab.`), para(elevatedCount ? `Foram identificadas ${elevatedCount} dimensão(ões) em nível médio, alto ou crítico, o que indica necessidade de tratamento estruturado e integração das medidas pertinentes ao GRO/PGR.` : "Não foram identificadas dimensões classificadas como risco Médio, Alto ou Crítico no consolidado organizacional. O cenário requer manutenção dos controles existentes e monitoramento preventivo."), para(`${principal.name} apresentou a maior média (${principal.mean.toFixed(2).replace(".", ",")}) e constitui o principal fator do cenário avaliado. ${secondary ? `${secondary.name} apresentou a segunda maior média (${secondary.mean.toFixed(2).replace(".", ",")}).` : ""} A posição relativa desses fatores orienta a priorização preventiva mesmo quando a classificação permanece baixa.`), para(`A avaliação contou com ${drps.respondent_count} resposta(s) válida(s) e abrangeu estrutura com ${structure.sectors.length} setor(es), ${structure.ghes.length} GHE(s) e ${structure.job_roles.length} função(ões) cadastrada(s). Foram concluídas ${completed.length} de ${aep.length} AEP-PS previstas, com ${allEvidence} evidência(s) anexada(s).`), statusParagraph,
      section("5", "APRESENTAÇÃO"), para(`O presente Relatório Técnico Integrado de Riscos Psicossociais consolida a avaliação realizada na ${company.legal_name}, integrando a percepção coletiva obtida pelo DRPS, a análise técnica da atividade e da organização real do trabalho registrada nas AEP-PS e as evidências disponíveis por GHE.`, { before: 130 }), para("A avaliação dos fatores psicossociais deve considerar como o trabalho é planejado, distribuído, comunicado, supervisionado e efetivamente executado. Por isso, resultados quantitativos não são interpretados isoladamente: sua leitura é confrontada com as condições observadas, os relatos coletados, os controles existentes e as particularidades dos grupos avaliados."), para("Este documento fornece subsídios para a tomada de decisão da empresa contratante e para a integração dos fatores e medidas aplicáveis ao Gerenciamento de Riscos Ocupacionais e ao Programa de Gerenciamento de Riscos. As recomendações têm caráter técnico e orientativo; cabe à organização definir responsáveis internos, recursos e cronograma de implementação."), para("Os resultados representam as condições e percepções existentes no período da avaliação. Não constituem diagnóstico clínico, laudo individual, comprovação de nexo causal ou conclusão isolada sobre assédio ou conduta específica."),
      section("6", "OBJETIVO"), para("Identificar, avaliar e priorizar fatores psicossociais relacionados à organização do trabalho; integrar os resultados do DRPS às AEP-PS e evidências; reconhecer convergências, divergências e lacunas; e propor medidas, indicadores e prazos orientativos para análise e implementação pela empresa contratante.", { before: 130 }), subsection("Objetivos específicos"), para("Os objetivos específicos compreendem: caracterizar o cenário psicossocial geral e os recortes tecnicamente válidos; analisar as dez dimensões e seus fatores de maior relevância; considerar a atividade real, os controles existentes e as evidências dos GHEs; estabelecer prioridades preventivas compatíveis com o nível de risco; subsidiar o inventário de riscos e o plano de ação do PGR; e orientar critérios de monitoramento e reavaliação."),
      section("7", "METODOLOGIA"), subsection("7.1 – Diagnóstico de Riscos Psicossociais (DRPS)"), para("O DRPS utiliza questionário estruturado em dez dimensões e escala tipo Likert de 1 a 5. As respostas são convertidas conforme a parametrização metodológica, consolidadas sem identificação pessoal e analisadas por médias, probabilidade, severidade e classificação de risco."), subsection("7.2 – Avaliação Ergonômica Preliminar Psicossocial (AEP-PS)"), para("A AEP-PS é realizada por GHE e registra a análise técnica da atividade real e da organização do trabalho. Os itens são avaliados em escala de 0 a 3, acompanhados, quando aplicável, de descrições, controles existentes, notas técnicas e evidências documentais ou de campo."), subsection("7.3 – Integração DRPS × AEP-PS"), para("Os instrumentos não são somados por média matemática. A integração verifica se a percepção coletiva e os achados técnicos apontam na mesma direção. Convergências desfavoráveis reforçam a prioridade; divergências exigem aprofundamento do contexto e das evidências; convergências favoráveis orientam a manutenção dos controles."), subsection("7.4 – Confidencialidade e limites"), para(`O ciclo utiliza mínimo de ${cycle.minimum_respondents} respondentes para agregação anônima. Recortes abaixo desse limite não devem ser apresentados como resultado coletivo individualizável. A interpretação também considera limitações de participação, qualidade dos registros e AEP-PS ainda pendentes.`),
      section("8", "REFERÊNCIAS TÉCNICAS E LEGAIS"), para("A análise foi estruturada com base nas diretrizes aplicáveis da NR-01 — Gerenciamento de Riscos Ocupacionais e PGR; NR-17 — Ergonomia; orientações oficiais relativas aos fatores de riscos psicossociais relacionados ao trabalho; ISO 45003 — gestão da saúde e segurança psicológica; HSE Management Standards Indicator Tool; e instrumentos DRPS e AEP-PS da metodologia Sealab.", { before: 130 }), para("A aplicação dessas referências é orientativa e deve ser compatibilizada com o contexto, o porte, os processos, os requisitos legais aplicáveis e as demais avaliações ocupacionais da organização."),
      section("9", "PERFIL DA AMOSTRA E ABRANGÊNCIA"), subsection("9.1 – Participação na avaliação"), participationTable, para(`A avaliação DRPS contou com ${drps.respondent_count} resposta(s) válida(s). ${participationRate === undefined ? "Não foi possível calcular a taxa de participação porque o efetivo total não está integralmente informado." : `Considerando o efetivo cadastrado nos GHEs, a taxa estimada de participação foi de ${participationRate.toFixed(1).replace(".", ",")}%.`} A abrangência deve ser interpretada conjuntamente com a distribuição dos trabalhadores entre setores e GHEs.`), subsection("9.2 – Análise da amostra"), para(`A estrutura avaliada possui ${structure.sectors.length} setor(es), ${structure.ghes.length} GHE(s) e ${structure.job_roles.length} função(ões). Em grupos com quantidade reduzida de respostas, os dados devem permanecer agregados e qualquer leitura que permita inferir respostas individuais deve ser evitada.`), table(aepRows, aepW), para("A situação das AEP-PS acima demonstra a cobertura da etapa técnica de campo. GHEs pendentes mantêm o RTIRP em condição parcial e devem ser concluídos antes da validação definitiva do ciclo.", { color: MUTED, size: 16 }),
      section("10", "RESULTADO GERAL DA EMPRESA"), subsection("10.1 – Análise do resultado"), para(`O resultado geral foi classificado como ${riskLabel[drps.overall_risk]}, com índice ${drps.general_mean.toFixed(2).replace(".", ",")}. O fator com maior média foi ${principal.name}, classificado como ${riskLabel[principal.risk]}. Conforme a metodologia, essa classificação representa ${riskMeaning[principal.risk]}.`), para(`A leitura comparativa mostra ${principal.name} e ${secondary?.name ?? principal.name} como fatores de maior relevância relativa. Essa priorização não altera automaticamente a classificação do risco, mas direciona a observação técnica, a manutenção ou revisão de controles e o monitoramento.`), table(intRows, intW), subsection("10.2 – Interpretação técnica por fator"), ...rankedDimensions.flatMap((item, index) => [subsection(`10.2.${index + 1} – ${item.name}`), para(`${item.name} avalia ${factorDescriptions[item.code] ?? "aspectos da organização do trabalho"}. A média registrada foi ${item.mean.toFixed(2).replace(".", ",")}, com probabilidade ${item.probability}, severidade ${item.severity} e classificação ${riskLabel[item.risk]}. O resultado indica ${riskMeaning[item.risk]}.`), para(`${item.status} na integração com a AEP-PS. Encaminhamento técnico: ${item.referral.toLowerCase()}. ${actions[item.code] ?? "Recomenda-se avaliar medidas preventivas compatíveis com os achados."}`)]), para("A matriz e as análises devem ser interpretadas como relação técnica entre percepção coletiva, avaliação de campo e evidências disponíveis, não como comprovação isolada de causalidade, adoecimento ou conduta individual.", { color: MUTED, size: 16, before: 90, after: 150 }),
      section("11", "MATRIZ DE PRIORIZAÇÃO DE AÇÕES"), levelTable, subsection("11.1 – Interpretação dos níveis de ação"), para("A classificação orienta a urgência e a natureza das medidas. Riscos críticos e altos requerem prioridade; riscos médios requerem plano estruturado; riscos baixos requerem manutenção e monitoramento; condições irrelevantes permanecem aceitáveis enquanto o contexto e os controles não se alterarem."), subsection("11.2 – Descrição dos fatores psicossociais avaliados"), descriptionTable, subsection("11.3 – Fatores organizacionais prioritários identificados"), table(riskRows, riskW), para(flagged.length ? "Os fatores apresentados foram selecionados por convergência desfavorável ou divergência entre DRPS e AEP-PS." : "Como não houve convergência desfavorável ou divergência prioritária, foram selecionados os fatores de maior média para acompanhamento preventivo, sem alteração da respectiva classificação de risco."),
      section("12", "PLANO DE AÇÃO CONSOLIDADO"), para("O plano abaixo apresenta recomendações técnicas destinadas a orientar a empresa contratante. A Sealab não realiza o acompanhamento operacional das ações; a organização deverá avaliar a aplicabilidade, designar responsáveis, disponibilizar recursos, registrar evidências e verificar a eficácia das medidas."), table(recRows, recW), subsection("12.1 – Diretrizes para implementação"), para("As medidas devem atuar preferencialmente sobre a organização do trabalho e sobre as fontes geradoras, respeitando a hierarquia de prevenção. A definição final deverá considerar viabilidade técnica, participação dos trabalhadores, interação com outros riscos ocupacionais e compatibilidade com os processos existentes."), para("Os prazos são orientativos: imediato para situações críticas; até 90 dias para prioridades altas; até 180 dias para condições médias ou necessidades estruturadas; e revisão periódica para condições baixas. A empresa poderá ajustar o cronograma mediante justificativa e registro no PGR."),
      section("13", "MONITORAMENTO DA EFICÁCIA DAS AÇÕES"), para("A implementação deverá ser verificada por indicadores e evidências compatíveis com cada medida, incluindo revisão de procedimentos, comunicação aos trabalhadores, registros de orientação ou treinamento, adequação de processos, observação das condições reais e percepção dos grupos envolvidos."), para(`Recomenda-se atenção aos fatores ${principal.name}${secondary ? ` e ${secondary.name}` : ""}, que apresentaram as maiores médias. O monitoramento deve avaliar não apenas a execução formal das medidas, mas sua capacidade de reduzir ou controlar as condições que originaram a recomendação.`), para("A reaplicação do DRPS e a revisão das AEP-PS são recomendadas preferencialmente em periodicidade anual ou antecipadamente diante de mudanças relevantes na estrutura, processos, efetivo, jornada, tecnologia, gestão, atividades ou condições de trabalho."), para("A Sealab fornece o direcionamento técnico e o parecer integrado. A definição dos responsáveis internos, o acompanhamento operacional, a guarda das evidências e a atualização do PGR cabem à empresa contratante."),
      section("14", "CONCLUSÃO TÉCNICA – ANÁLISE ORGANIZACIONAL E COMPORTAMENTAL"), para(`A avaliação permitiu caracterizar o cenário psicossocial da ${company.legal_name} por meio da integração entre percepção coletiva, análise técnica por GHE e evidências disponíveis. O consolidado apresentou índice ${drps.general_mean.toFixed(2).replace(".", ",")} e classificação ${riskLabel[drps.overall_risk]}.`), para(elevatedCount ? `Foram identificadas ${elevatedCount} dimensão(ões) em nível médio, alto ou crítico. Esses resultados requerem análise das fontes organizacionais, definição das medidas indicadas e integração formal ao inventário de riscos e ao plano de ação do PGR.` : "Não foram identificadas dimensões em nível médio, alto ou crítico no consolidado. O resultado aponta cenário globalmente favorável, sem afastar a necessidade de manutenção dos controles, escuta dos trabalhadores e acompanhamento preventivo."), para(`${principal.name}, com média ${principal.mean.toFixed(2).replace(".", ",")}, foi o fator de maior relevância relativa. ${secondary ? `${secondary.name}, com média ${secondary.mean.toFixed(2).replace(".", ",")}, ocupou a segunda posição.` : ""} Recomenda-se que esses fatores sejam acompanhados em conjunto com a atividade real, os controles existentes e as mudanças organizacionais futuras.`), para(`A integração identificou ${integration.filter((item) => item.status === "Convergência de risco").length} convergência(s) de risco, ${integration.filter((item) => item.status === "Divergência").length} divergência(s), ${integration.filter((item) => item.status === "Convergência favorável").length} convergência(s) favorável(is) e ${integration.filter((item) => item.status === "Pendente").length} dimensão(ões) pendente(s) de integração. Convergências desfavoráveis reforçam prioridades; divergências exigem aprofundamento técnico; pendências limitam a conclusão definitiva.`), para("Sob a perspectiva organizacional e comportamental, recomenda-se preservar práticas de comunicação clara, participação, apoio das lideranças e equipes, definição de atribuições, reconhecimento, respeito interpessoal, segurança psicológica e equilíbrio das demandas. Tais fatores são dinâmicos e podem se alterar com mudanças na organização do trabalho."), para("Os achados constituem subsídio técnico preventivo e não devem ser utilizados para individualização, diagnóstico clínico, atribuição automática de causalidade ou conclusão isolada sobre assédio. Situações específicas devem seguir os canais e procedimentos próprios de comunicação, acolhimento, investigação e tratamento da organização."), para("Conclui-se que os resultados e recomendações deste RTIRP devem ser considerados na revisão do GRO/PGR, em conjunto com as demais avaliações ocupacionais e evidências da empresa. A efetividade das medidas deverá ser verificada pela contratante e o ciclo reavaliado quando houver mudanças relevantes ou conforme a periodicidade definida."),
      section("15", "EVIDÊNCIAS E RESPONSABILIDADES TÉCNICAS"), subsection("15.1 – Inventário de evidências consideradas"), ...(evidenceRows.length > 1 ? [table(evidenceRows, evidenceW)] : [para("Não há arquivos de evidência anexados ao ciclo. A ausência deve ser considerada uma limitação e as evidências relevantes deverão ser registradas pela equipe técnica.")]), subsection("15.2 – Responsabilidades técnicas e aprovação"), para("Área reservada para identificação e aplicação das assinaturas digitais dos responsáveis técnicos. Após a assinatura, recomenda-se preservar a versão final em formato não editável e verificar a validade dos certificados utilizados.", { color: MUTED, size: 16 }), table([new TableRow({ children: [cell("ELABORAÇÃO", 5383, { bold: true, fill: LIGHT, align: AlignmentType.CENTER }), cell("REVISÃO / VALIDAÇÃO TÉCNICA", 5383, { bold: true, fill: LIGHT, align: AlignmentType.CENTER })] }), new TableRow({ height: { value: 2200, rule: HeightRule.ATLEAST }, children: [new TableCell({ width: { size: 5383, type: WidthType.DXA }, borders, verticalAlign: VerticalAlign.BOTTOM, margins: { top: 180, bottom: 180, left: 180, right: 180 }, children: [para("Nome / função / registro profissional", { align: AlignmentType.CENTER, size: 17, after: 60 }), para("ESPAÇO RESERVADO PARA ASSINATURA DIGITAL", { bold: true, color: MUTED, align: AlignmentType.CENTER, size: 15, after: 0 })] }), new TableCell({ width: { size: 5383, type: WidthType.DXA }, borders, verticalAlign: VerticalAlign.BOTTOM, margins: { top: 180, bottom: 180, left: 180, right: 180 }, children: [para("Nome / função / registro profissional", { align: AlignmentType.CENTER, size: 17, after: 60 }), para("ESPAÇO RESERVADO PARA ASSINATURA DIGITAL", { bold: true, color: MUTED, align: AlignmentType.CENTER, size: 15, after: 0 })] })] })], [5383, 5383]),
    ]
  } else {
    children = [...children, meta, para("", { after: 100 }), section("1", "RESUMO EXECUTIVO"), para(`O ciclo possui ${drps.respondent_count} respostas válidas, índice geral ${drps.general_mean.toFixed(2).replace(".", ",")} e classificação ${riskLabel[drps.overall_risk]}.`, { before: 130 }), statusParagraph, section("2", "SITUAÇÃO DAS AEP-PS POR GHE"), table(aepRows, aepW), para("", { after: 100 }), section("3", "MATRIZ DRPS × AEP-PS"), table(intRows, intW), para("Não é calculada média matemática entre DRPS e AEP-PS.", { color: MUTED, size: 16, before: 90, after: 150 }), section("4", "ORIENTAÇÕES À EMPRESA CONTRATANTE"), table(recRows, recW)]
  }
  return Packer.toBlob(new Document({ creator: "Sealab", title, features: { updateFields: true }, styles: { default: { document: { run: { font: "Arial", size: 19, color: INK }, paragraph: { alignment: AlignmentType.JUSTIFIED, spacing: { after: 110, line: 276 } } } } }, sections: [{ properties: { titlePage: true, page: { size: { width: 11906, height: 16838 }, margin: { top: 900, bottom: 900, left: 570, right: 570, header: 450, footer: 450 } } }, headers: { default: header, first: blankHeader }, footers: { default: footer, first: blankFooter }, children }] }))
}

export async function generateIntegratedWordReport(input: Omit<Input, "logoData">) {
  const logoData = await fetch("/assets/images/sealab-logo-report.png").then((response) => response.arrayBuffer()).catch(() => undefined)
  const flowData = input.mode === "rtirp" ? await fetch("/assets/images/fluxo-metodologico-rtirp.png").then((response) => response.arrayBuffer()).catch(() => undefined) : undefined
  const blob = await build({ ...input, logoData, flowData })
  const link = document.createElement("a")
  link.href = URL.createObjectURL(blob)
  link.download = `${input.mode === "rtirp" ? "RTIRP" : "Integracao-PGR"}-${safe(input.company.trade_name || input.company.legal_name)}-${safe(input.cycle.name)}.docx`
  link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000)
}
